version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - /home/table-price/mongodb/database:/data/db
    ports:
      - 30001:27017
    restart: unless-stopped
